// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsZNwj_S1o03jqDDziFnlt4ApTGzbEiM',
    appId: '1:744728658266:web:eb036ef1689855c01db363',
    messagingSenderId: '744728658266',
    projectId: 'kryptaecc',
    authDomain: 'kryptaecc.firebaseapp.com',
    storageBucket: 'kryptaecc.firebasestorage.app',
    measurementId: 'G-G0CLBCE7LP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5jL3OJVfjRbcXiSJep0VewDE88sW9F9M',
    appId: '1:744728658266:android:97bb34cb5e91b5e51db363',
    messagingSenderId: '744728658266',
    projectId: 'kryptaecc',
    storageBucket: 'kryptaecc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTM-5IYH88f61lZId6OKyqZ-wenJ9QQE',
    appId: '1:744728658266:ios:ac1b6bc4ad4873061db363',
    messagingSenderId: '744728658266',
    projectId: 'kryptaecc',
    storageBucket: 'kryptaecc.firebasestorage.app',
    iosBundleId: 'com.calcchat.ww',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTM-5IYH88f61lZId6OKyqZ-wenJ9QQE',
    appId: '1:744728658266:ios:8e946cdfa08eec121db363',
    messagingSenderId: '744728658266',
    projectId: 'kryptaecc',
    storageBucket: 'kryptaecc.firebasestorage.app',
    iosBundleId: 'com.example.kryptaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIsZNwj_S1o03jqDDziFnlt4ApTGzbEiM',
    appId: '1:744728658266:web:6cad5d69137c36c01db363',
    messagingSenderId: '744728658266',
    projectId: 'kryptaecc',
    authDomain: 'kryptaecc.firebaseapp.com',
    storageBucket: 'kryptaecc.firebasestorage.app',
    measurementId: 'G-PSK1M8YJ3G',
  );
}
